openapi: 3.1.1
info:
  title: weather-service-project
  version: 0.0.1
  description: HTTP server that serves the forecasted weather
servers:
  - url: http://127.0.0.1:5000/
paths:
  $ref: ./paths/_index.yaml
components:
  schemas:
    $ref: ./schemas/_index.yaml
